covidcombat/covidcombat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('covidcombatapp.urls')),
]

covidcombat/covidcombatapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('', views.home, name = 'home'),
    path('register/', views.register, name = 'register'),
    path('login/', auth_views.LoginView.as_view(template_name='covidcombatapp/login.html'), name='login'),
    path('examine', views.examine, name = 'examine'),
    path('test', views.test, name = 'test'),
    path('home', auth_views.LogoutView.as_view(template_name='covidcombatapp/home.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='covidcombatapp/password_reset.html'), name='password_reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(template_name='covidcombatapp/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='covidcombatapp/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='covidcombatapp/password_reset_complete.html'), name='password_reset_complete'),
    path('recovery', views.recovery, name = 'recovery'),
    path('vaccination', views.vaccination, name = 'vaccination'),
]

covidcombat/covidcombatapp/models.py
from django.db import models

class Examine(models.Model):
	Name = models.CharField(max_length=20, null=True, unique=True)
	temperature = models.IntegerField()
	dry_cough = models.BooleanField()
	taste = models.BooleanField()
	breathless = models.BooleanField()

	def __str__(self):
		return self.Name 


RESULT = [
		('Positive', 'Positive'),
        ('Negative', 'Negative')
    ]

OXYGEN = [
	('95 or above', '95 or above'),
    ('Below 95', 'Below 95')
]


class FinalTest(models.Model):
    
	Name = models.CharField(max_length=20, null=True, unique=True)
	test_result = models.CharField(max_length=20, null=True, choices=RESULT)
	oxygen_level = models.CharField(max_length=20, null=True, choices=OXYGEN)

	def __str__(self):
		return self.Name

covidcombat/covidcombatapp/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from . models import Examine, FinalTest


class UserRegisterForm(UserCreationForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']


class ExamineForm(ModelForm):
	
	class Meta:
		model = Examine
		fields = '__all__'		


class FinalTestForm(ModelForm):
	
	class Meta:
		model = FinalTest
		fields = '__all__'	

covidcombat/covidcombatapp/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, ExamineForm, FinalTestForm
from . models import Examine, FinalTest

def home(request):
	return render(request, 'covidcombatapp/home.html')

def register(request):
	if request.method == 'POST':
		form = UserRegisterForm(request.POST)
		
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			messages.success(request, f'Your account has been created! You can now login')
			return redirect('login')
	else:	
		form = UserRegisterForm()
	return render(request, 'covidcombatapp/register.html', { 'form': form })

@login_required
def examine(request):

	record = Examine.objects.all().filter(Name = request.user.get_username())
	final_record = FinalTest.objects.all().filter(Name = request.user.get_username())

	if request.method == 'POST':
		form = ExamineForm(request.POST)
		
		if form.is_valid():
			form.save()
			Name = form.cleaned_data.get('Name')
			temperature = request.POST.get('temperature')
			dry_cough = form.cleaned_data.get('dry_cough')
			taste = form.cleaned_data.get('taste')
			breathless = form.cleaned_data.get('breathless')
			
			if(int(temperature) <= 38 and dry_cough == False and taste == False
					and breathless == False):
				if len(record) > 0:
					record[0].delete()
				messages.success(request, f'You seem absolutely fine! Come back later and take a test if you feel unwell.')	
				return redirect('examine')		

			return redirect('examine')
	else:	
		form = ExamineForm()

	if request.method == 'POST':
		form_final = FinalTestForm(request.POST)
		
		if form_final.is_valid():
			form_final.save()
			Name = form_final.cleaned_data.get('Name')
			test_result = request.POST.get('test_result')

			if test_result == 'Negative':
				messages.success(request, f'You seem absolutely fine! Come back later and take a test if you feel unwell.')
				return redirect('test')
				
			return redirect('recovery')
	else:	
		form_final = FinalTestForm()	

	if len(final_record) > 0:
		return redirect('recovery')

	return render(request, 'covidcombatapp/examine.html', { 'form': form, 
															'form_final':form_final, 
															'record':record })

@login_required
def test(request):

	record = Examine.objects.all().filter(Name = request.user.get_username())
	final_record = FinalTest.objects.all().filter(Name = request.user.get_username())

	if len(record) > 0:
		record[0].delete()

	if len(final_record) > 0:
		final_record[0].delete()	
	
	if request.method == 'POST':
		form = ExamineForm(request.POST)
		
		if form.is_valid():
			form.save()
			Name = form.cleaned_data.get('Name')
			return redirect('examine')
	else:	
		form = ExamineForm()
	return render(request, 'covidcombatapp/examine.html', { 'form': form })

@login_required
def recovery(request):

	final_record = FinalTest.objects.all().filter(Name = request.user.get_username())

	return render(request, 'covidcombatapp/recovery.html', { 'final_record': final_record })

def vaccination(request):
	
	return render(request, 'covidcombatapp/vaccination.html')	

covidcombat/covidcombatapp/templates/covidcombatapp/examine.html
{% extends "covidcombatapp/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
 

        {% if record.0.Name|length %}
          
          <section class="page-section portfolio" id="portfolio" style="padding-left: 150px;">
        <main role="main" class="container"><br><br>

            <div class="row" style="height: 500px; width: 1000px;
              transform-style: preserve-3d;
              border-radius: 32px;
              box-shadow:
                1px 1px 0 1px #f9f9fb,
                -1px 0 28px 0 rgba(34, 33, 81, 0.01),
                28px 28px 28px 0 rgba(34, 33, 81, 0.25);
              transition:
                .4s ease-in-out transform,
                .4s ease-in-out box-shadow;

              &:hover {
                transform:
                  translate3d(0px, -16px, 0px)
                  rotateX(51deg)
                  rotateZ(43deg);
                box-shadow:
                  1px 1px 0 1px #f9f9fb,
                  -1px 0 28px 0 rgba(34, 33, 81, 0.01),
                  54px 54px 28px -10px rgba(34, 33, 81, 0.15);
              
              }">
                <div class="col-md-6"><br>
                  <form method="POST">
                    {% csrf_token %}
                    <fieldset class="form group">
                        <legend class="border-bottom mb-4">Fill in the below details</legend>
                         
                          <div class=""> 
                            <input type="hidden" name="Name" maxlength="20" class="textinput textInput form-control" required="" id="id_Name" value="{{ user.get_username }}" readonly> 
                          </div> 

                        <div id="div_id_test_result" class="form-group"> 
                          <label for="id_test_result" class=" requiredField">
                            Enter your Covid-19 test result<span class="asteriskField">*</span> 
                          </label> 
                          <div class=""> 
                            <select name="test_result" class="select form-control" required="" id="id_test_result"> 
                              <option value="" selected="">---------</option> 
                              <option value="Positive">Positive</option> 
                              <option value="Negative">Negative</option>
                            </select> 
                          </div> 
                        </div> 
                        <br>
                        <div id="div_id_oxygen_level" class="form-group">
                          <label for="id_oxygen_level" class=" requiredField">
                            Enter your SpO<sub>2</sub> level (Oxygen level)<span class="asteriskField">*</span>
                          </label> 
                          <div class=""> 
                            <select name="oxygen_level" class="select form-control" required="" id="id_oxygen_level"> <option value="" selected="">---------</option> <option value="95 or above">95 or above</option> <option value="Below 95">Below 95</option>
                            </select> 
                          </div> 
                        </div>

                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-primary" type="submit">Next</button>
                    </div>  
                  </form>
                </div>

            <div class="col-md-6">
                <br><h1>What Next ?</h1><br>
                <h5>1. Get a Covid-19 test done from a nearby centre</h5>
                <br><h5>2. Enter your test result here.</h5>
                <br><h5>3. Check your oxygen level with an Oximeter</h5>
                <br><h5>4. Fill the oxygen level field with correct range.</h5>
                <br><h5>5. Click on next to get further instructions.</h5>
            </div>

        </div>
        <br>

        <section class="page-section portfolio" id="portfolio">
              <br><div class="container">
                  <!-- Portfolio Section Heading-->
                  <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Testing Centers</h2>
                  <!-- Icon Divider-->
                  <div class="divider-custom">
                      <div class="divider-custom-line"></div>
                      <div class="divider-custom-icon"><i class="fas fa-plus-circle"></i></div>
                      <div class="divider-custom-line"></div>
                  </div>
                  <h5 style="padding-left: 10px;">Enter your current location or postal code below to get details of nearby testing centers</h5>
                  <div style="padding-right: 100px;">
                    <iframe width="100%" height="425" src="https://maps.mapmyindia.com/covid-places/embed?category=HSPTST" allow="geolocation" >
                    </iframe>
                  </div>
              </div>
    </section>
    </main>
    </section>

        {% else %}
          
          <section class="page-section portfolio" id="portfolio">
            <div class="container"><br>
                <!-- Portfolio Section Heading-->

                {% if messages %}
                    {% for message in messages%}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor%}
                {% endif %}

                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Examine your health</h2>
                <!-- Icon Divider-->
                <div class="divider-custom">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-plus-circle"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <div style="padding-left: 200px;">
                <main role="main" class="container">
              <div class="row">
                  <div class="col-md-10" style="height: 350px; width: 500px;
              transform-style: preserve-3d;
              border-radius: 32px;
              box-shadow:
                1px 1px 0 1px #f9f9fb,
                -1px 0 28px 0 rgba(34, 33, 81, 0.01),
                28px 28px 28px 0 rgba(34, 33, 81, 0.25);
              transition:
                .4s ease-in-out transform,
                .4s ease-in-out box-shadow;

              &:hover {
                transform:
                  translate3d(0px, -16px, 0px)
                  rotateX(51deg)
                  rotateZ(43deg);
                box-shadow:
                  1px 1px 0 1px #f9f9fb,
                  -1px 0 28px 0 rgba(34, 33, 81, 0.01),
                  54px 54px 28px -10px rgba(34, 33, 81, 0.15);
              
              }"><br>
              <table>
                <tr>
                  <td style="width: 250px;">
            <form method="POST">
                    {% csrf_token %}
                        
                        <input type="hidden" id="id_Name" name="Name" value="{{ user.get_username }}" readonly><br>
                        
                        <div id="div_id_temperature" class="form-group">
                    <label for="id_temperature" class=" requiredField">
                        Body Temperature(In Celcius)<span class="asteriskField">*</span>
                    </label>
                        <div class="">
                            <input type="number" name="temperature" class="numberinput form-control" required="" id="id_temperature" min="35" max="45">
                        </div>
              </div>

              <div class="form-group">
                <div id="div_id_dry_cough" class="form-check">
                    <input type="checkbox" name="dry_cough" class="checkboxinput form-check-input" id="id_dry_cough">
                            
                        <label for="id_dry_cough" class="form-check-label">
                            Do you have dry cough?
                        </label>
                </div>
                </div>

                <div class="form-group">
                <div id="div_id_taste" class="form-check">
                          <input type="checkbox" name="taste" class="checkboxinput form-check-input" id="id_taste">        
                        <label for="id_taste" class="form-check-label">
                            Do you experience loss of taste?
                        </label>
                </div>
                </div>

                <div class="form-group">
                <div id="div_id_breathless" class="form-check">
                    <input type="checkbox" name="breathless" class="checkboxinput form-check-input" id="id_breathless">
                        <label for="id_breathless" class="form-check-label">
                            Do you feel breathless?
                        </label>
                </div>
                </div>

                        <button id="submit" type="submit" class="btn btn-primary">Submit</button>
                </form>
              </td>
              <td>
                <div class="col-md-12" style="padding-left: 100px;">
                  <br><br><h6>1. Check your body temperature and enter the value in celcius degree.</h6><br>
                  <h6>2. Enter other details.</h6><br>
                  <h6>3. Click Submit.</h6><br>
                  <h6>4. Proceed according to your results.</h6>
              </div>
              </td>
            </tr>
          </table>
                </div>
                
                </div>
                </main> 
                </div>          
            </div>
        </section>

        {% endif %}

        <script>
        	
        	function examine(){
        		var temperature = {{ record.0.temperature }};
        		var cough = "\"{{ record.0.dry_cough }}\"";
            var taste = "\"{{ record.0.taste }}\"";
            var breathless = "\"{{ record.0.breathless }}\"";  
            
            if (temperature > 38 && cough == "\"True\"" && taste == "\"True\"" && breathless == "\"True\""){
              alert("It seems you are symptomatic. It is advised you take a Covid-19 test and come back with results.");
            }
            
            else if(temperature > 38 && cough == "\"True\"" && taste == "\"True\""){
              alert("It seems you are symptomatic. It is advised you take a Covid-19 test and come back with results.");
            }

            else if(temperature > 38 && taste == "\"True\"" && breathless == "\"True\""){
              alert("It seems you are symptomatic. It is advised you take a Covid-19 test and come back with results.");
            }

            else if(temperature > 38 && cough == "\"True\"" && breathless == "\"True\""){
              alert("It seems you are symptomatic. It is advised you take a Covid-19 test and come back with results.");
            }

            else if(cough == "\"True\"" && taste == "\"True\"" && breathless == "\"True\""){
              alert("It seems you are symptomatic. It is advised you take a Covid-19 test and come back with results.");
            }

            else if(cough == "\"True\"" && taste == "\"True\""){
              alert("It seems you are symptomatic. It is advised you take a Covid-19 test and come back with results.");
            }

            else if(taste == "\"True\"" && breathless == "\"True\""){
              alert("It seems you are symptomatic. It is advised you take a Covid-19 test and come back with results.");
            }

            else if(cough == "\"True\"" && breathless == "\"True\""){
              alert("It seems you are symptomatic. It is advised you take a Covid-19 test and come back with results.");
            }

            else if(temperature > 38 && cough == "\"True\""){
              alert("It seems you are symptomatic. It is advised you take a Covid-19 test and come back with results.");
            }

            else if(temperature > 38 && taste == "\"True\""){
              alert("It seems you are symptomatic. It is advised you take a Covid-19 test and come back with results.");
            }

            else if(temperature > 38 && breathless == "\"True\""){
              alert("It seems you are symptomatic. It is advised you take a Covid-19 test and come back with results.");
            }

            else if(temperature > 38){
              alert("It seems you are symptomatic. It is advised you take a Covid-19 test and come back with results.");
            }    

            else{
              alert("You look fine. Come back and take a test later if you feel discomfort.");
            }

        	}
        </script>

{% endblock content %}

covidcombat/covidcombatapp/templates/covidcombatapp/home.html
{% extends "covidcombatapp/base.html" %}
{% load static %}
{% block content %}
    
    <!-- Masthead-->
        <header class="masthead bg-primary text-white text-center">
            <div class="container d-flex align-items-center flex-column">
                <!-- Masthead Avatar Image-->
                <img class="masthead-avatar mb-5" src="{% static 'covidcombatapp/assets/img/main.png' %}" alt="..." />
                <!-- Masthead Heading-->
                <h1 class="masthead-heading text-uppercase mb-0">Covid Combat</h1>
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-plus-circle"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Masthead Subheading-->
                <p class="masthead-subheading font-weight-light mb-0">Examine - Prepare - Treat</p>
            </div>
        </header>

        <!-- Portfolio Section-->
        <section class="page-section portfolio" id="portfolio">
            <div class="container">
                <!-- Portfolio Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Dashboard</h2>
                <!-- Icon Divider-->
                <div class="divider-custom">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-plus-circle"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Portfolio Grid Items-->
                <div class="row justify-content-center">
                    <iframe src="https://ourworldindata.org/grapher/total-cases-covid-19?tab=map" width="100%" height="600px"></iframe>
                </div>
            </div>
        </section>

        <!-- About Section-->
        <section class="page-section bg-primary text-white mb-0" id="about">
            <div class="container">
                <!-- About Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-white">What to do?</h2>
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-plus-circle"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- About Section Content-->
                <div class="row">
                    <img src="{% static 'covidcombatapp/assets/img/flow.jpg' %}" width="1200" height="250" >
                </div>
            </div>
        </section>

        <!-- Contact Section-->
        <section class="page-section" id="contact">
            <div class="container">
                <!-- Contact Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Top News</h2>
                <!-- Icon Divider-->
                <div class="divider-custom">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-plus-circle"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Contact Section Form-->
                <div>
                    <table>
                        <tr>
                            <td>
                                <iframe width="560" height="315" src="https://health.economictimes.indiatimes.com/widget/diagnostics" frameborder="0"></iframe>
                            </td>

                            <td>
                                <iframe width="560" height="315" src="https://health.economictimes.indiatimes.com/widget/hospitals" frameborder="0"></iframe>
                            </td>    
                        </tr>
                    </table>
                    
                </div>
            </div>
        </section>

{% endblock %}

covidcombat/covidcombatapp/templates/covidcombatapp/login.html
{% extends "covidcombatapp/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<section class="page-section portfolio" id="portfolio">
	{% if messages %}
        {% for message in messages%}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor%}
    {% endif %}
    	<br><br>
        <main role="main" class="container" style="padding-left: 400px;">
            <div class="row" style="height: 425px; width: 400px;
						  transform-style: preserve-3d;
						  border-radius: 32px;
						  box-shadow:
						    1px 1px 0 1px #f9f9fb,
						    -1px 0 28px 0 rgba(34, 33, 81, 0.01),
						    28px 28px 28px 0 rgba(34, 33, 81, 0.25);
						  transition:
						    .4s ease-in-out transform,
						    .4s ease-in-out box-shadow;

						  &:hover {
						    transform:
						      translate3d(0px, -16px, 0px)
						      rotateX(51deg)
						      rotateZ(43deg);
						    box-shadow:
						      1px 1px 0 1px #f9f9fb,
						      -1px 0 28px 0 rgba(34, 33, 81, 0.01),
						      54px 54px 28px -10px rgba(34, 33, 81, 0.15);
						  
						  }">
                <div class="col-md-12" >
                <!-- Portfolio Section Heading-->
                <form method="POST">
				{% csrf_token %}
				<fieldset class="form group">
					<legend class="border-bottom mb-4">Log In</legend>
					{{ form|crispy }}
				</fieldset>
				<div class="form-group">
					<button class="btn btn-outline-info type="submit">Login</button>
					<small class="text-muted ml-2">
						<a href="{% url 'password_reset' %}">Forgot Password?</a>
					</small>
				</div>	
			</form>
			<div class="border-top pt-3">
				<small class="text-mutted">
					Don't have an account? <a class="ml-2" href="{% url 'register' %}">Sign Up</a>
				</small>			
			</div>
	        </div>
	    </div>
	    <!-- </div> -->
    </main>
    </section>
{% endblock content  %}

covidcombat/covidcombatapp/templates/covidcombatapp/password_reset.html
{% extends "covidcombatapp/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

	<section class="page-section portfolio" id="portfolio">
        <main role="main" class="container"><br><br>
            <div class="row">
                <div class="col-md-12" style="height: 225px; width: 475px;
                          transform-style: preserve-3d;
                          border-radius: 32px;
                          box-shadow:
                            1px 1px 0 1px #f9f9fb,
                            -1px 0 28px 0 rgba(34, 33, 81, 0.01),
                            28px 28px 28px 0 rgba(34, 33, 81, 0.25);
                          transition:
                            .4s ease-in-out transform,
                            .4s ease-in-out box-shadow;

                          &:hover {
                            transform:
                              translate3d(0px, -16px, 0px)
                              rotateX(51deg)
                              rotateZ(43deg);
                            box-shadow:
                              1px 1px 0 1px #f9f9fb,
                              -1px 0 28px 0 rgba(34, 33, 81, 0.01),
                              54px 54px 28px -10px rgba(34, 33, 81, 0.15);
                          
                          }"><br>
                <!-- Portfolio Section Heading-->
                <table>
                <tr>
                    <td style="width: 500px;">    
                    <form method="POST">
    					{% csrf_token %}
    					<fieldset class="form group">
    						<legend class="border-bottom mb-4">Reset Password</legend>
    						{{ form|crispy }}
    					</fieldset>
    					<div class="form-group">
    						<button class="btn btn-outline-info type="submit">Request Password Reset</button>
    					</div>	
    				</form>
                </td>

                <td style="padding-left: 50px;">
                    <h5>1. Enter your registered Email Id</h5><br>
                <h5>2. You will receive a mail with a password reset link</h5>
                <br><h5>3. Click on the link to reset your password</h5>
                </td>
            </tr>
            </table>
            </div>
        </div>
    </main>
    </section>	
{% endblock content  %}

covidcombat/covidcombatapp/templates/covidcombatapp/password_reset_complete.html
{% extends "covidcombatapp/base.html" %}

{% block content %}
	<section class="page-section portfolio" id="portfolio">
        <main role="main" class="container">
            <div class="row">
                <div class="col-md-6"><br>
                <div class="alert alert-info">
					Your password has been reset.	
				</div>
				<a href="{% url 'login' %}" style="font-size: 20px;">Log In Here</a>
			            </div>
            <div class="col-md-6">
                <br><br><h4>We lost</h4><br>
                <h3>We suffered</h3><br>
                <h2>But we keep fighting</h2>
            </div>
        </div>
    </main>
    </section>			
{% endblock content  %}

covidcombat/covidcombatapp/templates/covidcombatapp/password_reset_confirm.html
{% extends "covidcombatapp/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
		<section class="page-section portfolio" id="portfolio" style="padding-left: 500px;">
        <main role="main" class="container"><br>
            <div class="row">
                <div class="col-md-6" style="height: 425px; width: 600px;
                          transform-style: preserve-3d;
                          border-radius: 32px;
                          box-shadow:
                            1px 1px 0 1px #f9f9fb,
                            -1px 0 28px 0 rgba(34, 33, 81, 0.01),
                            28px 28px 28px 0 rgba(34, 33, 81, 0.25);
                          transition:
                            .4s ease-in-out transform,
                            .4s ease-in-out box-shadow;

                          &:hover {
                            transform:
                              translate3d(0px, -16px, 0px)
                              rotateX(51deg)
                              rotateZ(43deg);
                            box-shadow:
                              1px 1px 0 1px #f9f9fb,
                              -1px 0 28px 0 rgba(34, 33, 81, 0.01),
                              54px 54px 28px -10px rgba(34, 33, 81, 0.15);
                          
                          }"><br>
                <form method="POST">
					{% csrf_token %}
					<fieldset class="form group">
						<legend class="border-bottom mb-4">Reset Password</legend>
						{{ form|crispy }}
					</fieldset>
					<div class="form-group">
						<button class="btn btn-outline-info type="submit">Request Password Reset</button>
					</div>	
				</form>
            </div>
            <div class="col-md-6">
                
            </div>
        </div>
    </main>
    </section>	
{% endblock content  %}

covidcombat/covidcombatapp/templates/covidcombatapp/password_reset_done.html
{% extends "covidcombatapp/base.html" %}

{% block content %}
	<section class="page-section portfolio" id="portfolio">
        <main role="main" class="container">
            <div class="row">
                <div class="col-md-6"><br>
                <div class="alert alert-info">
					An email has been sent with intructions to reset your password.	
				</div>
            </div>
            <div class="col-md-6">
                <br><br><h4>We lost</h4><br>
                <h3>We suffered</h3><br>
                <h2>But we keep fighting</h2>
            </div>
        </div>
    </main>
    </section>				
{% endblock content  %}